#! /usr/bin/perl

use IO::Socket;

my $host='localhost';
my $port=6057;

my $server =
new IO::Socket::INET(PeerAddr=>$host, PeerPort=>$port, Proto=>'tcp')
||die "Socket: $!\n";

select($server);$|=1;select(STDOUT);

$buf=<$server>;

print $server "Locker takashi\n";

$buf=<$server>;chop($buf);s/\r//;
unless($buf =~ /Ok:$/){
	close($server);
	die "$buf\n";
}

print "$buf\n";

while(1){
	print "Input dead lock time.(sec) CR=Quit\n";
	$tm=<STDIN>;
	chomp($tm);$tm=~ s/\r//;
	if($tm eq ''){last;}
	print $server "term1 Sl";
	sleep($tm);
	print $server "ept $tm sec.\n";
}

close($server);
