#! /usr/bin/perl

use strict;
use constant KEYMIN => 10;
use constant KEYMAX => 18;


my $kcount = shift(@ARGV);

unless($kcount){
    print "Create ID keys.\n";
    print "Usage: $0 keycount\n";
    exit(1);
}
srand(time()^($$+($$<<15)));

my $lp;
my $ry;
my $lp2;
my $buf;
my $rd;
my $klen;
for($lp=0;$lp<$kcount;$lp++){
    $klen = int(rand(KEYMAX - KEYMIN)) + KEYMIN;
    $buf='';
    for($lp2=0;$lp2<$klen;$lp2++){
	$rd = int(rand 93)+33;
	if($rd >= 0x60){$rd++;}
	$buf .= sprintf("%c",$rd);
    }
    print "$buf\n";
}


